import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import ThemeProvider from "./components/ThemeProvider";
import ProgressProvider from "./components/ProgressProvider";
import Header from "./components/Header";
import Footer from "./components/Footer";
import TailwindIndicator from "./components/TailwindIndicator";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SpeedInsights />
        <ThemeProvider attribute="class" enableSystem={false}>
          <ProgressProvider>
            <Header />
            <main className="static mx-auto max-w-5xl px-8 py-24 md:mb-16">
              {children}
            </main>
            <Footer />
            <TailwindIndicator />
          </ProgressProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
